version: '3'
services:
  symptom_checker:
    image: python:3.9-slim
    container_name: symptom_checker_app
    stdin_open: true
    tty: true
    volumes:
      - .:/app  # Map the entire project root
    working_dir: /app
    command: streamlit run app.py
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: postgres:13
    container_name: symptom_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: symptomdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data